AppModelBundle\Entity\User:
    type: entity
    table: fos_user
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false
            length: 45
            fixed: false
        lastname:
            type: string
            nullable: true
            length: 45
            fixed: false
        daybirth:
            type: date
            nullable: true
        avatar:
            type: string
            nullable: true
            length: 45
            fixed: false
        settings:
            type: array
            nulleable: true
    lifecycleCallbacks: {  }
